CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR (100) UNIQUE NOT NULL,
  password VARCHAR(500) NOT NULL
);

CREATE TABLE log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR (100) NOT NULL,
  action VARCHAR(50) NOT NULL,
  user_agent VARCHAR(200) NOT NULL,
  entry_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(username) REFERENCES user(username)
);

CREATE TABLE messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR (100) NOT NULL,
  msg_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  msg VARCHAR(500) NOT NULL,
  FOREIGN KEY(username) REFERENCES user(username)
);



