name: Make and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: bash install_actions_deps.sh 1>/dev/null
    - name: Run Tests
      run: make test
